### ISSUE TITLE
Unpassender Service für Serving-Layer

### ISSUE THREAD

**Issue by hey-nicolasklein** [htw-swa-jk-nk-ns/voting-app#1]
Serving Layer sollte den Standard Service ClusterIP (und nicht LoadBalancer) nutzen. LoadBalancer ist für externe Services, die von außerhalb des Clusters angesprochen werden. Wenn kein spezial Type genannt wird, ists automatisch Cluster-IP. Auch Cluster-IP routet den Traffic zu den verschiedenen Instanzen. 

Änderung im Deployment des serving-layer wäre :

```
[ ... ]
---
apiVersion: v1
kind: Service
metadata:
  name: service-serving-layer-service
spec:
  selector:
    app: service-serving-layer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
```

aus der [Doku](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)

> Kubernetes ServiceTypes allow you to specify what kind of Service you want. The default is ClusterIP.
> 
> Type values and their behaviors are:
> 
> **ClusterIP**: Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster. This is the default ServiceType.
> **NodePort**: Exposes the Service on each Node's IP at a static port (the NodePort). A ClusterIP Service, to which the NodePort Service routes, is automatically created. You'll be able to contact the NodePort Service, from outside the cluster, by requesting <NodeIP>:<NodePort>.
> **LoadBalancer**: Exposes the Service externally using a cloud provider's load balancer. NodePort and ClusterIP Services, to which the external load balancer routes, are automatically created.
